data:

- alias: Dream3d
  url: >
    http://www.bluequartz.net/
  gist:
  - 02f6ee2e621cb3ed43f9
  tags:
  - metals
  - simulation
  - experiment
  - software
  - spatial
- alias: Citrination
  url: >
    http://www.citrination.com/
  gist:
  - #
  tags:
  - properties
- alias: Harvard Clean Energy Project
  url: >
    http://cleanenergy.molecularspace.org/
  gist:
  - b9e76659f8d5c5fd6e2c
  - 5642460f061a39d1820e
  tags:
  - electronic materials
  - simulation
  - experiment
- alias: MatWeb
  url: >
    http://www.matweb.com/
  gist:
  - 4ae9a7822f49a15a9ddd
  tags:
  - properties
- alias: AFLOW
  url: >
    http://materials.duke.edu/aflow.html
  gist:
  - 6b953ac03bfd6e99a3b7
  tags:
  - electronic materials
- alias: CALPHAD
  url: >
    http://www.calphad.org
  gist:
  - a7b20d089d84ed845796
  - e10da44fa023215cb28e
  - 11730086e9834d3bd2de
  tags:
  - first principles
  - ab initio
  - electronic
  - structural
  - LAMMPS
  - Molecular Dynamcis
- alias: MATERIALS ATLAS
  url: >
    https://cosmicweb.mse.iastate.edu/wiki/display/home/Materials+Atlas+Home
  gist:
  - 66b818c8c8bc539a9332
- alias: MATERIALS COMMONS
  url: >
    http://prisms.engin.umich.edu/#/prisms/materialscommons
  gist:
  - e4654be17c46394cc2d6
- alias: MATERIALS PROJECT
  url: >
    https://www.materialsproject.org
  gist:
  - 3e12df4295926d3e0a27
  - 4e4f8963fd3ca118fdc4
- alias: NIST DATABASES
  url: >
    http://srdata.nist.gov/gateway/gateway?dblist=0
  gist:
  - b3abac6743a7682def83
- alias: NIST Potentials Repository
  url: >
    www.ctcms.nist.gov/potentials/
  gist:
  - 6d4f0c3c4605e70e8443
  tags:
  - molecular dynamics
  - electronic potentials
- alias: THE OPEN QUANTUM MATERIALS DATABASE
  url: >
    http://oqmd.org
  gist:
  - b9e747e7424d643dd441
- alias: CMD Network
  url: >
    http://www.asminternational.org/web/cmdnetwork
  gist:
  - 8cafd0db00deca775724
